name: backend-ci-cd-dryrun

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # On est à la racine du repo ici
      - name: Debug repo tree
        run: |
          echo "PWD (repo root):"; pwd
          echo "List repo root:"; ls -la
          echo "List api/:"; ls -la api || true
          test -f api/pom.xml && echo "OK: api/pom.xml found" || (echo "KO: api/pom.xml missing" && exit 1)

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
          # chemin relatif à la racine du repo
          cache-dependency-path: api/pom.xml

      - name: Build and test (Maven)
        working-directory: api
        run: mvn -B -DskipTests=false verify

      - name: Collect artifact
        run: |
          mkdir -p out
          JAR_PATH=$(ls api/target/*.jar 2>/dev/null | head -n1 || true)
          if [ -n "$JAR_PATH" ]; then
            cp "$JAR_PATH" out/app-backend.jar
          else
            echo "(jar placeholder)" > out/app-backend.jar
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-dryrun-artifacts
          path: out/*
