name: backend-ci-cd-dryrun

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: api

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug repo tree
        run: |
          pwd
          ls -la
          echo "---- api dir ----"
          ls -la api || true
          test -f api/pom.xml && echo "OK: api/pom.xml found" || (echo "KO: api/pom.xml missing" && exit 1)

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: api/pom.xml  # <— important en monorepo

      - name: Build and test
        run: mvn -B -DskipTests=false verify

      - name: Collect artifact
        run: |
          mkdir -p ../out
          JAR_PATH=$(ls target/*.jar | head -n1 || true)
          if [ -n "$JAR_PATH" ]; then
            cp "$JAR_PATH" ../out/app-backend.jar
          else
            echo "(jar placeholder)" > ../out/app-backend.jar
          fi

      - name: Security dry run
        run: echo "[DRY-RUN] OWASP Dependency-Check / CodeQL" | tee -a ../out/security-backend.txt

      - name: Docker build dry run
        run: echo "[DRY-RUN] docker build -t example.local/cesizen-backend:${GITHUB_SHA} ." | tee -a ../out/docker.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-dryrun-artifacts
          path: out/*
