name: backend-ci-cd-dryrun

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      
name: Checkout
      uses: actions/checkout@v4

      
name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '21'

      
name: Cache Maven
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: m2-${{ hashFiles('**/pom.xml') }}

      
name: Build & test
      working-directory: api
      run: mvn -B -DskipTests=false verify

      
name: Collect artifact
      run: |
        mkdir -p out
        if ls api/target/.jar >/dev/null 2>&1; then
          cp api/target/.jar out/app-backend.jar
        else
          echo "(Jar d’exemple)" > out/app-backend.jar
        fi

      
name: Sécu — dry run
      run: echo "[DRY-RUN] OWASP Dependency-Check / CodeQL" | tee out/security-backend.txt

      
name: Docker build — dry run
      run: echo "[DRY-RUN] docker build -t example.local/cesizen-backend:${GITHUB_SHA} api" | tee -a out/docker.txt

      
name: Deploy — dry run
      run: echo "[DRY-RUN] ssh prod && docker compose up -d" | tee -a out/deploy.txt

      
name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: backend-dryrun-artifacts
        path: out/*