name: frontend-ci-cd-dryrun

on:
  push:
    branches: [ develop, main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: CESIZen-front

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: CESIZen-front/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build || (mkdir -p dist && echo "dist placeholder" > dist/index.html)

      - name: Pack artifacts
        run: |
          mkdir -p ../out
          tar -czf ../out/frontend-dist.tgz -C dist .

      - name: Security dry run
        run: |
          npm audit --audit-level=high || true
          echo "[DRY-RUN] audit done" > ../out/security-frontend.txt

      - name: Docker build dry run
        run: echo "[DRY-RUN] docker build -t example.local/cesizen-frontend:${GITHUB_SHA} ." | tee -a ../out/docker.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dryrun-artifacts
          path: out/*
